[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --omit=optional"]

[start]
cmd = "node backend/server.js"
